<a href="https://colab.research.google.com/github/25031554180-bit/Feature-Engineering/blob/main/Aliya(030)Restika(180).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



*   Aliya Munafi'ah(25031554030)
*   Restika Zakiyatus Syahida(25031554180)

In [ ]:
# CHAPTER 7 - TEXT SIMILARITY (EXERCISE 6)

Cosine Similarity contoh teks

In [ ]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

# Contoh data teks
documents = ["text data clustering", "text mining and data analysis", "clustering and classification"]

# Mengubah teks menjadi numerik
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(documents)

#df = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())
# Menghitung cosine similarity dan mengonversi ke jarak
similarity = cosine_similarity(X)
print(similarity)

[[1.         0.51639778 0.33333333]
 [0.51639778 1.         0.25819889]
 [0.33333333 0.25819889 1.        ]]

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer

# Contoh data teks
documents = ["text data clustering", "text mining and data analysis", "clustering and classification"]

# Mengubah teks menjadi matriks TF-IDF
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(documents)

# Menghitung cosine similarity dan mengonversi ke jarak
similarity = cosine_similarity(X)
print(similarity)

[[1.         0.4543876  0.29898437]
 [0.4543876  1.         0.20378218]
 [0.29898437 0.20378218 1.        ]]

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from scipy.spatial.distance import pdist

# Contoh data teks
documents = ["text data clustering", "text mining and data analysis", "clustering and classification"]

vectorizer = CountVectorizer(binary=True)
X = vectorizer.fit_transform(documents).toarray()
print(X)

# Menghitung jarak Cosine
distances = 1-pdist(X, metric='cosine')
#distance_matrix = squareform(distances)
print(distances)
#distance_matrix

[[0 0 0 1 1 0 1]
 [1 1 0 0 1 1 1]
 [0 1 1 1 0 0 0]]
[0.51639778 0.33333333 0.25819889]

Jaccard Similarity Contoh Teks

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import jaccard_score
from scipy.spatial.distance import pdist

# Contoh data teks
documents = ["text data clustering", "text mining and data analysis", "clustering and classification"]

vectorizer = CountVectorizer(binary=True)
X = vectorizer.fit_transform(documents).toarray()

# Menghitung jarak Jaccard
distances = pdist(X, metric='jaccard')
print(distances)

# Menghitung similarity antar document
Sd1d2 = jaccard_score(X[0], X[1]) #similarity doc 1 and doc 2
Sd1d3 = jaccard_score(X[0], X[2]) #similarity doc 1 and doc 3
Sd2d3 = jaccard_score(X[1], X[2]) #similarity doc 2 and doc 3

Sd1d2, Sd1d3, Sd2d3

[0.66666667 0.8        0.85714286]

(np.float64(0.3333333333333333),
 np.float64(0.2),
 np.float64(0.14285714285714285))

Scraping & Preprocessing Data Buku

In [ ]:

import requests
from bs4 import BeautifulSoup
import pandas as pd
import re
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
import nltk
from IPython.display import display, HTML

nltk.download('stopwords')

root = 'https://books.toscrape.com/catalogue/page-'
titles = []
for page in range(1, 6):
    url = requests.get(root + str(page) + '.html')
    soup = BeautifulSoup(url.text, 'html.parser')
    scrap = soup.find_all('article', {'class': 'product_pod'})
    for i in scrap:
        titles.append(i.find('h3').find('a')['title'])

data = pd.DataFrame({'Title': titles, 'summaries': titles})
print("Total rows : ", len(data))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

Total rows :  100

Cosine Similarity

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

stemmer = PorterStemmer()
stop_words = set(stopwords.words("english"))
corpus = []
for summary in data.summaries.to_list():
    tokens = summary.lower().split()
    # Stemming and stop-word removal
    tokens = [stemmer.stem(token) for token in tokens if token not in stop_words]
    corpus.append(" ".join(tokens))

# create a TF-IDF index based on the whole corpus
vectorizer = TfidfVectorizer(sublinear_tf=True, max_features=5000)
vectorizer.fit_transform(corpus)
# Print features used for TF-IDF vectorization
print("Total features ", vectorizer.get_feature_names_out().shape)

Total features  (406,)

In [ ]:
# Vectfrom sklearn.metrics.pairwise import cosine_similarity
documents_tfidf_features = vectorizer.transform(corpus)
TopK = 10
# sample query
query = "light attic story"
# query TF-IDF vector
query_tfidf_features = vectorizer.transform([query])
print("TF-IDF features for query", query_tfidf_features, "\n")
# Computing the cosine similarities
similarities = cosine_similarity(documents_tfidf_features, query_tfidf_features)
top_indices = similarities[:, 0].argsort()[::-1][:TopK] # Pick TopK document ids having highest cosine similarity
# Display the relevant documents
titles = []
abstracts = []
similarity = []

for doc_index in top_indices:
    titles.append(data.iloc[doc_index].Title)
    abstracts.append(data.iloc[doc_index].summaries.replace("\n", " "))
results = pd.DataFrame({"Title": titles, "Abstract": abstracts, "Similarities": similarities[top_indices, 0]})
display(HTML(results.to_html()))

TF-IDF features for query <Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2 stored elements and shape (1, 406)>
  Coords	Values
  (0, 33)	0.7071067811865476
  (0, 204)	0.7071067811865476

Jaccard Similarity

In [ ]:
stemmer = PorterStemmer()
stop_words = set(stopwords.words("english"))
corpus = []
for summary in data.summaries.to_list():
    tokens = summary.lower().split()
    # Stemming and stop-word removal
    tokens = [stemmer.stem(token) for token in tokens if token not in stop_words]
    corpus.append(" ".join(tokens))

# Vectorize the corpus using binary CountVectorizer for Jaccard Similarity
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(binary=True, max_features=5000)
documents_binarized_features = vectorizer.fit_transform(corpus).toarray()

# Print features used for vectorization
print("Total features ", vectorizer.get_feature_names_out().shape)

Total features  (406,)

In [ ]:
from scipy.spatial.distance import cdist

# Converting query to a binary vector
TopK = 10
query = "light attic story"
query_binarized_features = vectorizer.transform([query]).toarray()

# Calculating Jaccard Similarities
similarities = 1-cdist(documents_binarized_features, query_binarized_features, metric='jaccard')

# Get Top K most similar documents
top_indices = similarities[:, 0].argsort()[::-1][:TopK]

# Display relevant documents
titles = []
abstracts = []
similarity_scores = []

for doc_index in top_indices:
    titles.append(data.iloc[doc_index].Title)
    abstracts.append(data.iloc[doc_index].summaries.replace("\n", " "))
    similarity_scores.append(similarities[doc_index, 0])

# Create DataFrame for results
results = pd.DataFrame({"Title": titles, "Abstract": abstracts, "Similarities": similarity_scores})
display(HTML(results.to_html()))